# Generated by Django 5.0.2 on 2024-02-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('H', 'HeadPhone'), ('W', 'Watch'), ('E', 'Electronic'), ('M', 'Monitors'), ('T', 'Trending'), ('O', 'Other')], max_length=2),
        ),
    ]
